### ISSUE TITLE
When should it support Swift?

### ISSUE THREAD

**Issue by michaelmou** [travisjeffery/ClangFormat-Xcode#106]

**Comment by tonyarnold** [comment]
Probably never, unless the clang-format tool adds support for Swift. AFAIK, nobody is working on doing this at present — but I'd love to be wrong.

**Comment by travisjeffery** [comment]
yep, see -> https://github.com/travisjeffery/ClangFormat-Xcode/issues/55#issuecomment-66754367. 

cross your fingers, maybe send something to the clang mailing list.
