### ISSUE TITLE
Cannot install on Xcode 8

### ISSUE THREAD

**Issue by christophefondacci** [travisjeffery/ClangFormat-Xcode#123]
When trying to run ClangFormat on Xcode 8 to install the plugin it says:
Message from debugger: cannot attach to process due to System Integrity Protection

It works fine with Xcode 7.3. I don't want to disable SIP just for that but would love to be able to use ClangFormat on Xcode 8.

Any help / workaround? Thanks.

I tried the suggestion from #85 but same error.

**Comment by tonyarnold** [comment]
I talked to a number of engineers about this while at WWDC last week: there's no path forward for any existing Xcode plugin after Xcode 8 is released. Short of disabling SIP (don't do this), Xcode will not load third party xcplugins anymore.

It might be possible to write a simplified version of Clang Format using the new Source Editor Extension API.

**Comment by kkaefer** [comment]
See https://github.com/mapbox/XcodeClangFormat for a version that works in Xcode 8.

**Comment by guoranliaoran** [comment]
@kkaefer Thanks a lot，U are 666 in Chinese.

**Comment by lichon** [comment]
You can unsign the xcode binary to load the bundles
ref to : https://github.com/XVimProject/XVim/issues/988

**Comment by travisjeffery** [comment]
Updated docs for Xcode 8: https://github.com/travisjeffery/ClangFormat-Xcode#installation
