### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by sssilver** [travisjeffery/ClangFormat-Xcode#133]
Is this project still alive?

clang-format is at 8.0 now, this addon uses a hopelessly outdated version 5, and the repo doesn't seem to have been updated in a year.

Is someone still maintaining this?

**Comment by AhiyaHiya** [comment]
Judging by the lack of response, it would seem that the answer is no @sssilver :(

**Comment by tonyarnold** [comment]
It's not usable anymore. Apple nixed the undocumented plugin format that this project was using. 

I've used https://github.com/mapbox/XcodeClangFormat to good effect, but it probably needs some love.
