### ISSUE TITLE
"Use System ClangFormat" crashes Xcode

### ISSUE THREAD

**Issue by superlukas** [travisjeffery/ClangFormat-Xcode#41]
I'm using the clang-format that comes bundled with LLVM 3.4.1.
Here's the code that leads to the crash.

**Edit:** Just to be clear. Any code leads to a crash. The code below is just the smallest example I could think of to reproduce the error.

```cpp
// Foo.h
class Foo {
public:
void foo();
};
```

**Comment by Phenmod** [comment]
me 2

**Comment by jkyin** [comment]
Did you have install system clang-format?
