### ISSUE TITLE
ClangFormat incorrectly splits Objective-C string literals

### ISSUE THREAD

**Issue by ghost** [travisjeffery/ClangFormat-Xcode#46]
I cloned and pulled the latest release of ClangFormat, which still exhibits this bug.
An NSArray literal containing NSString literals before running ClangFormat:

```
  NSArray *testInputStrings = @[
    @"abcdefg",
    @"*^&I*BEI*BDI C# RG#RC#YJGR #",
    @"那隻敏捷的棕色狐狸跳線懶狗。",
    @"1",
    @"12",
    @"123",
    @"1234",
    @"12345",
    @"123456",
    @"1234567",
    @"12345678",
    @"123456789",
    @"1234567890",
 @"kljsadgflkuyaerkuqhfbdsalkfbalkshdeklahdskjbfaskljhraslkrhuwbdbhsCKJhbasjkhfawkjhgrkjaebfdjkahsbdfjkhawkjfegkqrwjygr3uy24764587321rgj32hvr4jkh2vrkj2vfqrfqwjkh*&^*^&*RIBIEBKHBDJHABJEHBjqdbwjy3egjwybdehjbdfjsdhbfjsehbfjhsbfsjhbfdjshbfsmdbfshfbejw3jbfdsmhbdmshbfs"
  ];
```

The same NSArray literal after running ClangFormat:

```
  NSArray *testInputStrings = @[
    @"abcdefg",
    @"*^&I*BEI*BDI C# RG#RC#YJGR #",
    @"那隻敏捷的棕色狐狸跳線懶狗。",
    @"1",
    @"12",
    @"123",
    @"1234",
    @"12345",
    @"123456",
    @"1234567",
    @"12345678",
    @"123456789",
    @"1234567890",
    @"kljsadgflkuyaerkuqhfbdsalkfbalkshdeklahdskjbfaskljhraslkrhuwbdbhsCKJhbasj"
    @"khfawkjhgrkjaebfdjkahsbdfjkhawkjfegkqrwjygr3uy24764587321rgj32hvr4jkh2vr"
    @"kj2vfqrfqwjkh*&^*^&*"
    @"RIBIEBKHBDJHABJEHBjqdbwjy3egjwybdehjbdfjsdhbfjsehbfjhsbfsjhbfdjshbfsmdbf"
    @"shfbejw3jbfdsmhbdmshbfs"
  ];
```

**Comment by timbodeit** [comment]
Have set `PenaltyBreakString: 2147483647` and clang-format is still breaking Objective-C string literals.

In my eyes, this issue should be reopened

**Comment by xilin** [comment]
It also seems to be a bug for me. I thought that `PenaltyBreakString ` should always have a higher priority than the `ColumnLimit `. Otherwise, is there a way for us to keep these two settings effective at the same time?

**Comment by tonyarnold** [comment]
> In my eyes, this issue should be reopened

It's not an issue with ClangFormat-Xcode. You need to [report these issues to the LLVM Bugzilla](https://llvm.org/bugs/index.cgi).
