### ISSUE TITLE
Can't find usable .clang-format

### ISSUE THREAD

**Issue by anilanar** [travisjeffery/ClangFormat-Xcode#68]
I put the following `.clang-format` file in both the project root directory and parent of that folder too.

    BasedOnStyle: LLVM

When I try to format, I get the error: `Can't find usable .clang-format, using LLVM style`.

Using XCode 6.1.1 and latest ClangFormat from Alcatraz.

**Comment by anilanar** [comment]
Sorry my bad, there was a typo in `.clang-format` file name.

**Comment by Guerrix** [comment]
@anilanar I'm having the same issue, but not able to solve it. What exactly did you do? Thanks

**Comment by anilanar** [comment]
The filename was wrong in my case: I think it was `clagn-format` instead of `clang-format` :+1:

**Comment by Guerrix** [comment]
@anilanar where it this file?.... Sorry bother you with this. :worried:

**Comment by anilanar** [comment]
Well you need to put it yourself into your project root. In my case it is:

`filename: AAKeyboardManager.clang-format`

```
BasedOnStyle: Google
ContinuationIndentWidth: 2

```

**Comment by Guerrix** [comment]
@anilanar Thanks a lot!!!  it's working now :smile:
