### ISSUE TITLE
Xcode scrolling on format.

### ISSUE THREAD

**Issue by Falven** [travisjeffery/ClangFormat-Xcode#78]
For those of us who use format on save, the fact that Xcode will scroll around the file when we save is a big distraction and problem. Don't know much about Xcode plugins, but could there be a conceivable way of preventing Xcode from scrolling around to a random place in the code when formatting? Or at least a hack-ish way where Xcode scrolls back to where your viewport was before it scrolled?

**Comment by scottsykora** [comment]
I second this issue. I'd love to see a fish for this, it is pretty disorienting every time i subconsciously hit command-s. I'm running Xcode 6.4 and seeing this.

**Comment by scottsykora** [comment]
Actually, I've found that this isn' an issue when the cursor is within the current scrolled to section of the file. If the cursor is outside then the formatter scrolls the window to the cursor, which is unexpected and disorienting.

**Comment by travisjeffery** [comment]
#93
