### ISSUE TITLE
cannot build for Xcode 6.3.2 (10.10.3)

### ISSUE THREAD

**Issue by nyotis** [travisjeffery/ClangFormat-Xcode#85]
i was using tool properly for previous versions, can anyone confirm successful build for latest Xcode?

**Comment by AdamWang1102** [comment]
I have same trouble with you,I can't see the Clang-format in Xcode -> Edit but sometimes when I save the file plugin could work sometimes it doesn't work.

**Comment by carloe** [comment]
+1

**Comment by AdamWang1102** [comment]
@carloe It works,Thank you very much!

**Comment by nyotis** [comment]
@carloe it's not working for me - i do restart xcode

**Comment by carloe** [comment]
@nyotis did you run the project after you added the UUID, but before you restarted Xcode? If you had previously installed ClangFormat via Alcatraz you may also need to remove the plugin from within Alcatraz before you add it manually, but I am not sure.

**Comment by slcott** [comment]
I have similar issues. I received a warning from XCode about plugins when restarting the application after updating to Version 6.3.2 (6D2105). I removed the plugin from the alcatraz "package manager" menu within XCode. I made sure that the plugin was manually removed from /Users/slcott/Library/Application Support/Developer/Shared/Xcode/Plug-ins
as well as from /Users/slcott/Library/Application Support/Alcatraz/Plug-ins
. I restarted XCode. Then reinstalled ClangFormat-Xcode and restarted XCode again. After all this, the formatter still did not appear in the "edit" menu.

**Comment by tonyarnold** [comment]
Hi guys, I've added the DVTPlugInCompatibilityUUID for Xcode 6.3.2 to the repo — a quick rebuild should fix the problems you're having. 

Fixed by 937ef3894ef75ceadf3a46d98067107fcabec776.

**Comment by slcott** [comment]
It works for me now. Thanks!

**Comment by beimen** [comment]
Xcode 6.3.2 is different from other versions.
After Xcode 6.3.2 installed, Xcode will find the plug-ins folder, if some plug-ins have the same DVTPlugInCompatibilityUUID for 6.3.2, Xcode will ask user to choose "Load Bundle" or "Skip Bundle", and "Skip Bundle" is recommended by Xcode.
If user choose "Skip Bundle", the plug-ins would not working, although they have the right DVTPlugInCompatibilityUUID.

**Comment by nyotis** [comment]
sure, it works fine now
