### ISSUE TITLE
Xcode 4.6 update issue

### ISSUE THREAD

**Issue by danielaguta** [travisjeffery/ClangFormat-Xcode#89]
Hi,

I updated my Xcode to 6.4 and the "Edit -> Clang Format" menu disappeared

<img width="1065" alt="screen shot 2015-07-06 at 16 16 03" src="https://cloud.githubusercontent.com/assets/3851689/8522859/67dddb16-23fa-11e5-9ca5-16245a10ba17.png">

I would successfully use the Clang-Formatter with the previous Xcode version

Any suggestions on how to fix this?

Thanks,
Daniela

**Comment by tonyarnold** [comment]
Hi Daniela, how did you originally install ClangFormat-Xcode? We've updated the repository to support Xcode 6.4, however you'll either need to recompile the plugin, or reinstall/update it via a tool like [Alcatraz](http://alcatraz.io/).

**Comment by danielaguta** [comment]
Hi,

I had previously cloned the repository, built and run ClangFormat then restarted Xcode
I am now using the latest commit:
https://github.com/travisjeffery/ClangFormat-Xcode/commit/54b31e83f71817014263d465aef7815c660e8c17
