### ISSUE TITLE
support for Xcode 7.0 beta?

### ISSUE THREAD

**Issue by nyotis** [travisjeffery/ClangFormat-Xcode#92]
it doesn't seem you already support  Xcode 7.0 beta, can you confirm?

**Comment by dubemikeTouchLab** [comment]
i also tried it, seems there is no support yet for xcode 7 beta

**Comment by tonyarnold** [comment]
We do as of about 30 seconds ago: 87ca56427afa2d41cd0ba68bd6c6677e15daeb07

**Comment by nyotis** [comment]
on the spot, thanks!

**Comment by nyotis** [comment]
Hi

Does this also work for the stable XCode 7?

**Comment by tonyarnold** [comment]
Yes, it should do — I'm using it now with Xcode 7.0.1 and 7.1.0b3.

**Comment by nyotis** [comment]
All good, cheers @tonyarnold 
(@jurre)
